services:
  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - backend/.env.test
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api
    restart: always
    build: ./backend
    ports:
      - 4000:4000
    env_file:
      - backend/.env.test
    depends_on:
      - postgres

volumes:
  postgres-data: