services:
  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./backend
    ports:
      - 4000:4000
    env_file:
      - backend/.env
    depends_on:
      - postgres

  spa:
    container_name: spa
    build: ./frontend
    volumes:
      - react-data:/var/www/html

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - react-data:/var/www/html
      - ssl-certs:/certs
    depends_on:
    - postgres
    - api
    - spa
    - openssl

volumes:
  postgres-data:
  react-data:
  ssl-certs: