name: Build and Deploy on AWS
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: self-hosted
        timeout-minutes: 10
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
              
            - name: create back-end env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                envkey_PORT: ${{secrets.PORT}}         
                envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
                envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USER}}
                envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
                envkey_POSTGRES_HOST: ${{secrets.POSTGRES_PASSWORD}}
                envkey_POSTGRES_PORT: 5432
                envkey_POSTGRES_DATABASE: ${{secrets.POSTGRES_DB}}
                directory: backend
                file_name: .env
                fail_on_empty: true

            - name: Create front-end envfile
              uses: SpicyPizza/create-envfile@v1.3
              with:
                VITE_REACTAPP_BACKEND_URL: ${{secrets.VITE_REACTAPP_BACKEND_URL}}
                directory: frontend
                file_name: .env
                fail_on_empty: true

            - name: Run Docker Compose Down
              run: docker compose down

            - name: Delete react docker volume
              run: if docker volume ls --quiet --filter name=afestas_react-volume | grep -q .; then docker volume rm afestas_react-volume; fi

            - name: Run Docker Compose Up and Build
              run: docker compose up --build -d
